Functional Kafka proxying, albeit with some classpath conflicts
For some reason all GW requests throw java.lang.NoSuchMethodError: kotlinx.coroutines.experimental.channels.ActorJob.join(Lkotlin/coroutines/experimental/Continuation;)Ljava/lang/Object;